# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000ms
  servlet:
    context-path: /meet

spring:
  profiles:
    active: dev
    # jackson时间格式化
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    #  redis:
    #    open: false  # 是否开启redis缓存  true开启   false关闭
    #    database: 0
    #    host: 192.168.1.88
    #    port: 6379
    #    password:    # 密码（默认为空）
    #    timeout: 6000ms  # 连接超时时长（毫秒）
    #    jedis:
    #      pool:
  mvc:
    throw-exception-if-no-handler-found: true

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.nc.meet.modules.app.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
# 分页插件配置
pagehelper:
  helperDialect: mysql #配置数据库方言
  params: count=countSql
  reasonable: true #分页合理化参数
  supportMethodsArguments: true #支持通过 Mapper 接口参数来传递分页参数

meet:
  redis:
    open: false
  shiro:
    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: 0e4857731d348910376d42323d0fe94a97100d5fa2c1bf562d7591d23159cbe5
    # token有效时长，7天，单位秒
    expire: 604800
    #expire: 60
    header: token
