spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: dm.jdbc.driver.DmDriver
      url: jdbc:dm://192.168.1.100:5237
      username: XXADSB
      password: Aa11111111
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

# 是否开启swagger，开发环境打开，线上关闭
nature:
  restApi:
    enabled: true
  # 项目名称
application:
  name: 空域管制系统
  # 项目版本信息
  version: 0.0.1
  # 项目描述信息
  description: 空域管制系统|接口文档

#报文解析接口
cat-socket:
  port: 8000 #服务端端口
  receive:
    #address: 127.0.0.1 #接收端ip
    address: 192.168.1.155 #接收端ip
    port: 9000 #接收端端口